name: Setup/Cache Env
description: 'Sets up and caches a python env. Will only install dependencies if no cache was hit.'


inputs:
    pyproject-file-path:
        required: False
        description: "Path to the pyproject.toml including filename"
        default: "./pyproject.toml"
runs:
    using: composite
    steps:
        - name: Setup Python from pyproject.toml
          uses: ./.github/actions/python_from_pyproject
          with:
              pyproject-file-path: ${{ inputs.pyproject-file-path }}

        -   name: Cache Env
            uses: actions/cache@v4.2.3
            id: env-cache
            with:
                path: ${{ env.pythonLocation }}
                key:  ${{ hashFiles('./requirements/requirements.txt') }}-${{ hashFiles('./requirements/requirements_test.txt') }}

        -   name: Install Dependencies
            if: ${{ steps.env-cache.outputs.cache-hit != 'true' }}
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements/requirements.txt
                pip install -r requirements/requirements_test.txt
            shell: bash