name: Create Master Cache

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - master

permissions:
      id-token: write
      contents: read

env:
    PYTEST_ADDOPTS: "--color=yes"

jobs:
  create_master_cache:
    name: Caching
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:

    - name: Check out Repo
      uses: actions/checkout@v4
      with:
       fetch-depth: 0

    - name: Setup Env
      uses: ./.github/actions/setup_env